### ISSUE TITLE
Get::Metas($type) 的作用

### ISSUE THREAD

**Issue by Sualiu** [ShuShuicu/Typecho-Theme-Development-Framework#2]
```
    // Metas
    public static function Metas($type) {
        try {
            return self::getWidget()->metas($type);
        } catch (Exception $e) {
            return self::handleError('获取Metas失败', $e, null);
        }
    }
```

这个函数方法类似于 `\Widget_Archive::widget('Widget_Archive')->metas();` ，可我实在没有在 typecho 中找到相关的方法，也没有在介绍中发现有关这个函数方法的说明。

由于是业余爱好者，常粗心大意，恐有疏漏，特来询问这个函数方法的作用。

**Comment by ShuShuicu** [comment]
可能是AI补代码后忘检直接提交了（滑稽.jpg）

**Comment by Sualiu** [comment]
😭

**Comment by Sualiu** [comment]
另外麻烦您看一下提交的 Pull requests 合适么

**Comment by ShuShuicu** [comment]
哇，遇到大佬了！这个框架是我之前写主题时突发奇想搞出来的。当时写的时候没考虑那么多甚至很多逻辑是自己写后用AI补全
![60CEE18CD3EDA4B4DF4E808314F74D83](https://github.com/user-attachments/assets/e56fb6fa-a1e9-47f2-8c5a-080e30306f5e)

**Comment by Sualiu** [comment]
不是什么大佬了，也是平时没事的时候写着玩的。代码什么的可能不是太专业，没有系统的学习过……


看到你的项目感觉很适合我这种懒癌加小白，毕竟Typecho文档真的匮乏喵。


那就一起共同努力喽


PS：这种pull requests可以么？可以的话，以后就按照这种提pull了。

**Comment by Sualiu** [comment]
不想的话说一下就OK哦，因为懒癌突发，近期不打算再提交了（

**Comment by ShuShuicu** [comment]
可以呀，这可太棒了！！！
